sudo: false
language: node_js
node_js:
  - "node"
os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run tslint
  - npm test --silent

before_deploy:
  - npm install -g vsce
  - vsce package

deploy:
  provider: releases
  api_key: "${GITHUB_DEPLOY_KEY}"
  file_glob: true
  file: 
    - "*.vsix"
  skip_cleanup: true
  draft: true
  name: "${TRAVIS_TAG}"
  on:
    tags: true
    condition: $TRAVIS_OS_NAME == "linux"
